/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Op = ">=" | "<=" | ">" | "<" | "==" | "!=";

/**
 * The result of evaluating a team-test suite against one team. Per-test pass/fail plus WITNESSES (which members satisfied a test; which group elements are uncovered). The witnesses are exactly what a future suggestion/optimizer consumes: for each failing test, search the legal candidate pool for mons that flip the failing predicate.
 */
export interface VGCTeamTestReport {
  schemaVersion?: string;
  /**
   * Suite name or id that was run.
   */
  suite: string;
  /**
   * The team under test: an opaque id, or a lightweight slot summary.
   */
  team?:
    | string
    | {
        slot: number;
        species: Id;
      }[];
  format?: string;
  generatedAt?: string;
  /**
   * True iff every error-severity test passed.
   */
  passed: boolean;
  summary?: {
    error?: Tally;
    warn?: Tally;
    info?: Tally;
  };
  results: Result[];
}
export interface Tally {
  passed?: number;
  failed?: number;
}
export interface Result {
  id: string;
  title?: string;
  severity?: "error" | "warn" | "info";
  weight?: number;
  pass: boolean;
  /**
   * The measured count/distinct-count for count-style assertions.
   */
  actual?: number;
  op?: Op;
  /**
   * The threshold compared against.
   */
  value?: number;
  /**
   * Members that satisfied the test's predicate (count/countDistinct/team).
   */
  satisfiedBy?: MemberRef[];
  /**
   * For coverage assertions: which group elements were/weren't handled.
   */
  coverage?: {
    of?: "all" | "any";
    atLeast?: number;
    covered?: string[];
    /**
     * The gap — drives the suggestion button / marilland-style highlighting.
     */
    uncovered?: string[];
    /**
     * element -> members that handled it.
     */
    byElement?: {
      [k: string]: MemberRef[];
    };
  };
  message?: string;
  /**
   * Free-form evaluator detail (e.g. damage rolls, computed speeds).
   */
  detail?: {
    [k: string]: unknown;
  };
}
export interface MemberRef {
  slot: number;
  species: Id;
}
