/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A canonical Showdown id: lowercase, alphanumerics only, no spaces or punctuation (e.g. 'Landorus-Therian' -> 'landorustherian', 'Freeze-Dry' -> 'freezedry', 'Choice Scarf' -> 'choicescarf').
 */
export type Id = string;
export type Nature =
  | "hardy"
  | "lonely"
  | "brave"
  | "adamant"
  | "naughty"
  | "bold"
  | "docile"
  | "relaxed"
  | "impish"
  | "lax"
  | "timid"
  | "hasty"
  | "serious"
  | "jolly"
  | "naive"
  | "modest"
  | "mild"
  | "quiet"
  | "bashful"
  | "rash"
  | "calm"
  | "gentle"
  | "sassy"
  | "careful"
  | "quirky";
export type TeraType =
  | "normal"
  | "fire"
  | "water"
  | "electric"
  | "grass"
  | "ice"
  | "fighting"
  | "poison"
  | "ground"
  | "flying"
  | "psychic"
  | "bug"
  | "rock"
  | "ghost"
  | "dragon"
  | "dark"
  | "steel"
  | "fairy"
  | "stellar";
/**
 * A definition key / reference (threat, group, predicate). Lowercase, may contain '-' and '_'.
 */
export type Name = string;
/**
 * A named set used by inGroup atoms (species kind) and coverage assertions (threats / values / meta kinds).
 */
export type Group =
  | SpeciesGroup
  | ThreatsGroup
  | MetaThreatsGroup
  | ValuesGroup;
export type ThreatRef = Name | Threat;
/**
 * A boolean expression over a single team member (or, in team scope, existentially over the team). Discriminated by 'kind'.
 */
export type Predicate =
  | All
  | Any
  | Not
  | AtLeastK
  | Ref
  | Species
  | Ability
  | Nature1
  | Gender
  | Level
  | Item
  | Move
  | Type
  | TeraType1
  | InGroup
  | Tagged
  | Stat
  | Outspeeds
  | TypeEffectiveness
  | ImmuneTo
  | CanRemove
  | Survives
  | Koes
  | DealsDamage
  | FoulPlay;
/**
 * @minItems 1
 */
export type PredicateList = [Predicate, ...Predicate[]];
export type Species = {
  [k: string]: unknown;
};
export type Ability = {
  [k: string]: unknown;
};
export type Nature1 = {
  [k: string]: unknown;
};
export type Gender1 = "M" | "F" | "N";
/**
 * Comparison operator for thresholds and numeric atoms.
 */
export type Op = ">=" | "<=" | ">" | "<" | "==" | "!=";
export type Item = {
  [k: string]: unknown;
};
export type Move = {
  [k: string]: unknown;
};
export type Type = {
  [k: string]: unknown;
};
export type TeraType1 = {
  [k: string]: unknown;
};
/**
 * Canonical Showdown stat key order (hp, atk, def, spa, spd, spe).
 */
export type StatKey = "hp" | "atk" | "def" | "spa" | "spd" | "spe";
/**
 * A named multiplier applied to a computed stat (mostly speed). Closed vocab the evaluator understands; extend here as needed.
 */
export type StatModifier =
  | "scarf"
  | "tailwind"
  | "paralysis"
  | "swift_swim"
  | "chlorophyll"
  | "sand_rush"
  | "slush_rush"
  | "surge_surfer"
  | "unburden"
  | "quark_drive_spe"
  | "protosynthesis_spe"
  | "choice_band"
  | "choice_specs"
  | "iron_ball"
  | "grass_pelt";
export type NameOrEach = Name | "$each";
/**
 * role:'defending' = the multiplier of incoming vsType against the member's typing (resist => <= 0.5). role:'attacking' = the member's effectiveness of vsType against the target. withTera evaluates the tera typing.
 */
export type TypeEffectiveness = {
  [k: string]: unknown;
};
/**
 * Member is immune to 'effect' (a key in data/interactions.json immunities) OR to a class of move via 'moveTag' (type/ability immunity, e.g. 'ohko'). Generic: new immunity sources are added in data, not here.
 */
export type ImmuneTo = {
  [k: string]: unknown;
};
/**
 * The quantifier + threshold. Exactly one of the four shapes.
 */
export type Assert =
  | CountAssertion
  | CountDistinctAssertion
  | CoverageAssertion
  | TeamAssertion;

/**
 * A declarative, composable suite of constraints ('unit tests') for a VGC (doubles, bring-6-choose-4) Pokemon team. Every test reduces to COUNT(members matching a predicate) compared to a threshold; meta-specific knowledge (what is 'speed control', what is immune to 'powder', threat spreads) lives in referenced reference data, not in this schema.
 */
export interface VGCTeamTestSuite {
  $schema?: string;
  /**
   * Free-text authoring note; ignored by evaluators.
   */
  $comment?: string;
  /**
   * Semantic version of this suite schema the document targets.
   */
  schemaVersion: string;
  name?: string;
  description?: string;
  /**
   * Showdown format id (e.g. 'gen9championsvgc2026regma'). Drives legality, EV model, and the usage-stats source for 'set: usage' threats. EV caps are format-driven and intentionally NOT enforced here.
   */
  format?: string;
  /**
   * Which metagame snapshot resolves 'set: usage' spreads and meta-derived threat groups.
   */
  meta?: {
    /**
     * e.g. '2026-05' — a usage-stats period.
     */
    snapshot?: string;
    /**
     * e.g. 'smogon-usage'.
     */
    source?: string;
    [k: string]: unknown;
  };
  /**
   * Relative paths to other suites whose tests/definitions are merged in before this one's (composition).
   */
  extends?: string[];
  /**
   * Reusable, named fragments referenced by tests.
   */
  definitions?: {
    /**
     * Named calc/speed targets. Reference by name from survives/koes/outspeeds/dealsDamage atoms.
     */
    threats?: {
      [k: string]: Threat;
    };
    /**
     * Named sets (species allow-lists, threat groups, value lists) used by inGroup atoms and coverage assertions.
     */
    groups?: {
      [k: string]: Group;
    };
    /**
     * Named reusable predicates, referenced via {"kind":"ref","predicate":"<name>"}.
     */
    predicates?: {
      [k: string]: Predicate;
    };
  };
  /**
   * @minItems 1
   */
  tests: [Test, ...Test[]];
}
/**
 * An opposing Pokemon used as a calc target and/or speed-tier comparand. Fields project directly onto @smogon/calc's Pokemon + Move + Field. The low-friction default is set:'usage' — name a species (and optionally a move) and let the meta fill the spread/item.
 */
export interface Threat {
  species: Id;
  /**
   * A canonical Showdown id: lowercase, alphanumerics only, no spaces or punctuation (e.g. 'Landorus-Therian' -> 'landorustherian', 'Freeze-Dry' -> 'freezedry', 'Choice Scarf' -> 'choicescarf').
   */
  move?: string;
  /**
   * 'usage' (the low-friction default) auto-fills spread + item from the suite's meta snapshot; any other value names a set preset.
   */
  set?: string;
  item?: Id;
  ability?: Id;
  nature?: Nature;
  evs?: EvSpread;
  ivs?: EvSpread;
  level?: number;
  teraType?: TeraType;
  /**
   * Whether the threat is Terastallized for this calc.
   */
  tera?: boolean;
  boosts?: Boosts;
  isCrit?: boolean;
  field?: FieldSpec;
  /**
   * Named (string) or inline variations expanded into multiple calc instances; survives/koes 'case' selects across them.
   */
  variations?: (Name | Variation)[];
}
/**
 * EV (or, in Champions formats, stat-point) investment. Caps are format-driven and not enforced here.
 */
export interface EvSpread {
  hp?: number;
  atk?: number;
  def?: number;
  spa?: number;
  spd?: number;
  spe?: number;
}
/**
 * Stat-stage boosts (-6..+6), e.g. {"atk": -1} for one Intimidate.
 */
export interface Boosts {
  atk?: number;
  def?: number;
  spa?: number;
  spd?: number;
  spe?: number;
  acc?: number;
  eva?: number;
}
/**
 * Battle field, projecting onto @smogon/calc Field. gameType defaults to doubles.
 */
export interface FieldSpec {
  gameType?: "singles" | "doubles";
  weather?: "sun" | "rain" | "sand" | "snow" | "none";
  terrain?: "electric" | "grassy" | "misty" | "psychic" | "none";
  trickRoom?: boolean;
  attackerSide?: SideSpec;
  defenderSide?: SideSpec;
}
/**
 * Side conditions, projecting onto @smogon/calc Side.
 */
export interface SideSpec {
  tailwind?: boolean;
  reflect?: boolean;
  lightScreen?: boolean;
  auroraVeil?: boolean;
  helpingHand?: boolean;
  friendGuard?: boolean;
  isProtected?: boolean;
}
/**
 * An override bundle applied on top of a threat to model a board state (e.g. afterIntimidate, plus1, helpingHand, rain). Inline, or referenced by name from data/threats.json variations.
 */
export interface Variation {
  name?: string;
  item?: Id;
  ability?: Id;
  boosts?: Boosts;
  field?: FieldSpec;
}
export interface SpeciesGroup {
  kind: "species";
  description?: string;
  /**
   * @minItems 1
   */
  members: [Id, ...Id[]];
}
export interface ThreatsGroup {
  kind: "threats";
  description?: string;
  /**
   * @minItems 1
   */
  members: [ThreatRef, ...ThreatRef[]];
}
export interface MetaThreatsGroup {
  kind: "meta";
  description?: string;
  from: "usage";
  topN?: number;
  minUsage?: number;
  /**
   * Which move each resolved threat attacks with: a heuristic or an explicit move id.
   */
  move?: ("bestDamaging" | "bestStab") | Id;
}
/**
 * A literal set of values (e.g. all 18 types) to iterate in coverage assertions; $each binds to each value.
 */
export interface ValuesGroup {
  kind: "values";
  description?: string;
  valueType: "type" | "move" | "item" | "ability" | "species";
  /**
   * @minItems 1
   */
  members: [string, ...string[]];
}
export interface All {
  kind: "all";
  of: PredicateList;
}
export interface Any {
  kind: "any";
  of: PredicateList;
}
export interface Not {
  kind: "not";
  of: Predicate;
}
export interface AtLeastK {
  kind: "atLeastK";
  k: number;
  of: PredicateList;
}
export interface Ref {
  kind: "ref";
  predicate: Name;
}
export interface Gender {
  kind: "gender";
  is: Gender1;
}
export interface Level {
  kind: "level";
  op: Op;
  value: number;
}
export interface InGroup {
  kind: "inGroup";
  group: Name;
}
/**
 * Member has an entity of type 'of' carrying 'tag' in data/tags.json. With facet+equals, that entity's facet value must equal 'equals'.
 */
export interface Tagged {
  kind: "tagged";
  of: "move" | "item" | "ability" | "species";
  tag: string;
  facet?: string;
  equals?: string | number | boolean;
}
/**
 * Compare a stat. vs:'base' uses the species base stat; vs:'final' computes the level-50 stat from EVs/IVs/nature, then applies 'mods' multipliers (scarf, tailwind, paralysis, weather speed abilities, ...).
 */
export interface Stat {
  kind: "stat";
  stat: StatKey;
  vs?: "base" | "final";
  mods?: StatModifier[];
  op: Op;
  value: number;
}
/**
 * Member's effective speed beats the threat's (the threat carries its own scarf/mods). underTrickRoom flips the comparison.
 */
export interface Outspeeds {
  kind: "outspeeds";
  threat: NameOrEach;
  /**
   * Modifiers applied to the MEMBER.
   */
  mods?: StatModifier[];
  /**
   * Treat a speed tie as success.
   */
  orSpeedTie?: boolean;
  underTrickRoom?: boolean;
}
/**
 * Member can remove a hazard (key in data/interactions.json hazardRemoval) — e.g. grounded-poison absorbs toxic spikes, or knows a remover move.
 */
export interface CanRemove {
  kind: "canRemove";
  hazard: string;
}
/**
 * Member survives the threat's hit(s) from full HP. 'case' selects across the threat's variations (worst = most damaging). roll:'max' = even the high roll leaves >0 HP (true survival).
 */
export interface Survives {
  kind: "survives";
  threat: NameOrEach;
  case?: "worst" | "best" | "specified";
  variation?: Name;
  roll?: "min" | "max" | "avg";
  hits?: number;
  withTera?: boolean;
}
/**
 * Member's best damaging move KOs the threat in 'hits' hits (1=OHKO, 2=2HKO). roll:'min' = guaranteed (even the low roll).
 */
export interface Koes {
  kind: "koes";
  threat: NameOrEach;
  hits?: number;
  roll?: "min" | "max";
  move?: Id;
  withTera?: boolean;
}
/**
 * Member deals at least/at most a fraction of the threat's HP with a (best or named) move.
 */
export interface DealsDamage {
  kind: "dealsDamage";
  threat: NameOrEach;
  move?: Id;
  roll?: "min" | "max" | "avg";
  fraction: {
    op: Op;
    value: number;
  };
}
/**
 * RESERVED future atom: a flaky signal from a battle-AI (foul-play / 'blackglasses') over a toy board state. Defined now so suites referencing it validate; use severity:'info'.
 */
export interface FoulPlay {
  kind: "foulPlay";
  scenario: string;
  threshold?: number;
  samples?: number;
}
export interface Test {
  id: string;
  title?: string;
  /**
   * Why this constraint matters — surfaced in reports.
   */
  rationale?: string;
  severity?: "error" | "warn" | "info";
  weight?: number;
  tags?: string[];
  assert: Assert;
}
/**
 * Number of team members satisfying 'where' (all members if omitted), compared to value.
 */
export interface CountAssertion {
  count: "members";
  where?: Predicate;
  op: Op;
  value: number;
}
/**
 * Number of DISTINCT values of an attribute among members (optionally filtered by 'where') — for 'multiple FORMS of X' (variety).
 */
export interface CountDistinctAssertion {
  /**
   * Attribute to count distinct values of: 'species' | 'item' | 'ability' | 'teraType' | 'type' | 'move' | 'facet:<facetKey>' (e.g. 'facet:speedControlKind').
   */
  countDistinct: string;
  where?: Predicate;
  op: Op;
  value: number;
}
/**
 * For {of} elements of a group, at least {atLeast} members satisfy 'each'. The current element binds to '$each' inside 'each'. Powers 'for every X, someone handles it' (the marilland premise, '2HKO every top-N').
 */
export interface CoverageAssertion {
  coverage: {
    group: Name;
    by?: "members";
    each: Predicate;
    atLeast?: number;
    of?: "all" | "any";
  };
}
/**
 * Whole-team escape hatch: a boolean combination of EXISTENTIAL member requirements. In team scope each member-atom means 'some member satisfies it', so all/any/not compose across DIFFERENT requirements, e.g. (someone has Fake Out) AND (someone has Trick Room).
 */
export interface TeamAssertion {
  team: Predicate;
}
