/**
 * Hand-written domain types for the evaluator.
 *
 * Note: types/suite.d.ts and types/report.d.ts (generated by
 * `npm run build:types` from the JSON Schemas) are the public schema
 * contract. They're intentionally not reused here — several nested
 * predicate fields collapse to `{[k: string]: unknown}` in the generated
 * output (a json-schema-to-typescript limitation on oneOf unions), which
 * isn't precise enough for the evaluator's switch-on-`kind` narrowing.
 * These types describe the same shapes with concrete fields instead.
 */

export type Op = ">=" | "<=" | ">" | "<" | "==" | "!=";

export type StatKey = "hp" | "atk" | "def" | "spa" | "spd" | "spe";

export type StatModifier =
  | "scarf"
  | "tailwind"
  | "paralysis"
  | "swift_swim"
  | "chlorophyll"
  | "sand_rush"
  | "slush_rush"
  | "surge_surfer"
  | "unburden"
  | "quark_drive_spe"
  | "protosynthesis_spe"
  | "choice_band"
  | "choice_specs"
  | "iron_ball"
  | "grass_pelt";

export interface EvSpread {
  hp?: number;
  atk?: number;
  def?: number;
  spa?: number;
  spd?: number;
  spe?: number;
}

export interface Boosts {
  atk?: number;
  def?: number;
  spa?: number;
  spd?: number;
  spe?: number;
  acc?: number;
  eva?: number;
}

export interface SideSpec {
  tailwind?: boolean;
  reflect?: boolean;
  lightScreen?: boolean;
  auroraVeil?: boolean;
  helpingHand?: boolean;
  friendGuard?: boolean;
  isProtected?: boolean;
}

export interface FieldSpec {
  gameType?: "singles" | "doubles";
  weather?: "sun" | "rain" | "sand" | "snow" | "none";
  terrain?: "electric" | "grassy" | "misty" | "psychic" | "none";
  trickRoom?: boolean;
  attackerSide?: SideSpec;
  defenderSide?: SideSpec;
}

export interface Variation {
  name?: string;
  item?: string;
  ability?: string;
  boosts?: Boosts;
  field?: FieldSpec;
}

export interface ThreatSpec {
  species: string;
  move?: string;
  set?: string;
  item?: string;
  ability?: string;
  nature?: string;
  evs?: EvSpread;
  ivs?: EvSpread;
  level?: number;
  teraType?: string;
  tera?: boolean;
  boosts?: Boosts;
  isCrit?: boolean;
  field?: FieldSpec;
  variations?: (string | Variation)[];
}

// ---------------------------------------------------------------------------
// Groups
// ---------------------------------------------------------------------------

export interface SpeciesGroup {
  kind: "species";
  description?: string;
  members: string[];
}
export interface ThreatsGroup {
  kind: "threats";
  description?: string;
  members: (string | ThreatSpec)[];
}
export interface MetaThreatsGroup {
  kind: "meta";
  description?: string;
  from: "usage";
  topN?: number;
  minUsage?: number;
  move?: "bestDamaging" | "bestStab" | string;
}
export interface ValuesGroup {
  kind: "values";
  description?: string;
  valueType: TaggableKind | "type";
  members: string[];
}
export type GroupSpec =
  | SpeciesGroup
  | ThreatsGroup
  | MetaThreatsGroup
  | ValuesGroup;

// ---------------------------------------------------------------------------
// Predicates
// ---------------------------------------------------------------------------

// The JSON Schema repeats the shapes below once per `oneOf` branch (it has
// no generics, so `$ref`-ing a shared subschema can't override `kind`'s
// `const`). TypeScript can parametrize on the discriminant directly, so the
// handful of atoms/composites that are otherwise identical are expressed as
// instances of a shared generic instead of being hand-copied.

/** Boolean composite over a list of sub-predicates, e.g. `all`/`any`. */
interface OfListPredicate<K extends string> {
  kind: K;
  of: Predicate[];
}
export type AllPredicate = OfListPredicate<"all">;
export type AnyPredicate = OfListPredicate<"any">;
export interface AtLeastKPredicate extends OfListPredicate<"atLeastK"> {
  k: number;
}
export interface NotPredicate {
  kind: "not";
  of: Predicate;
}
export interface RefPredicate {
  kind: "ref";
  predicate: string;
}

/** Exact-match (`is`) or membership (`in`) test over a single string attribute. */
interface IsInPredicate<K extends string> {
  kind: K;
  is?: string;
  in?: string[];
}
export type SpeciesPredicate = IsInPredicate<"species">;
export type AbilityPredicate = IsInPredicate<"ability">;
export type NaturePredicate = IsInPredicate<"nature">;
export type TeraTypePredicate = IsInPredicate<"teraType">;
export interface ItemPredicate extends IsInPredicate<"item"> {
  present?: boolean;
}

export interface GenderPredicate {
  kind: "gender";
  is: "M" | "F" | "N";
}
export interface LevelPredicate {
  kind: "level";
  op: Op;
  value: number;
}

/** "Knows one move" (`has`) or "knows any of" (`hasAny`) test, plus an atom-specific third option. */
interface HasAnyPredicate<K extends string> {
  kind: K;
  has?: string;
  hasAny?: string[];
}
export interface MovePredicate extends HasAnyPredicate<"move"> {
  hasAll?: string[];
}
export interface TypePredicate extends HasAnyPredicate<"type"> {
  isExactly?: string[];
}

export interface InGroupPredicate {
  kind: "inGroup";
  group: string;
}

/** Entity kinds that carry `data/tags.json` taxonomy tags. */
export type TaggableKind = "move" | "item" | "ability" | "species";

export interface TaggedPredicate {
  kind: "tagged";
  of: TaggableKind;
  tag: string;
  facet?: string;
  equals?: string | number | boolean;
}

export interface StatPredicate {
  kind: "stat";
  stat: StatKey;
  vs?: "base" | "final";
  mods?: StatModifier[];
  op: Op;
  value: number;
}

export interface OutspeedsPredicate {
  kind: "outspeeds";
  threat: string;
  mods?: StatModifier[];
  orSpeedTie?: boolean;
  underTrickRoom?: boolean;
}

export interface TypeEffectivenessPredicate {
  kind: "typeEffectiveness";
  role: "defending" | "attacking";
  vsType: string;
  withTera?: boolean;
  op: Op;
  value: number;
}

export interface ImmuneToPredicate {
  kind: "immuneTo";
  effect?: string;
  moveTag?: string;
  move?: string;
}

export interface CanRemovePredicate {
  kind: "canRemove";
  hazard: string;
}

export interface SurvivesPredicate {
  kind: "survives";
  threat: string;
  case?: "worst" | "best" | "specified";
  variation?: string;
  roll?: "min" | "max" | "avg";
  hits?: number;
  withTera?: boolean;
}

export interface KoesPredicate {
  kind: "koes";
  threat: string;
  hits?: number;
  roll?: "min" | "max";
  move?: string;
  withTera?: boolean;
}

export interface DealsDamagePredicate {
  kind: "dealsDamage";
  threat: string;
  move?: string;
  roll?: "min" | "max" | "avg";
  fraction: { op: Op; value: number };
}

export interface FoulPlayPredicate {
  kind: "foulPlay";
  scenario: string;
  threshold?: number;
  samples?: number;
}

export type Predicate =
  | AllPredicate
  | AnyPredicate
  | NotPredicate
  | AtLeastKPredicate
  | RefPredicate
  | SpeciesPredicate
  | AbilityPredicate
  | NaturePredicate
  | GenderPredicate
  | LevelPredicate
  | ItemPredicate
  | MovePredicate
  | TypePredicate
  | TeraTypePredicate
  | InGroupPredicate
  | TaggedPredicate
  | StatPredicate
  | OutspeedsPredicate
  | TypeEffectivenessPredicate
  | ImmuneToPredicate
  | CanRemovePredicate
  | SurvivesPredicate
  | KoesPredicate
  | DealsDamagePredicate
  | FoulPlayPredicate;

// ---------------------------------------------------------------------------
// Assertions / tests / suite
// ---------------------------------------------------------------------------

export interface CountAssertion {
  count: "members";
  where?: Predicate;
  op: Op;
  value: number;
}
export interface CountDistinctAssertion {
  countDistinct: string;
  where?: Predicate;
  op: Op;
  value: number;
}
export interface CoverageAssertion {
  coverage: {
    group: string;
    by?: "members";
    each: Predicate;
    atLeast?: number;
    of?: "all" | "any";
  };
}
export interface TeamAssertion {
  team: Predicate;
}
export type Assert =
  | CountAssertion
  | CountDistinctAssertion
  | CoverageAssertion
  | TeamAssertion;

export interface Test {
  id: string;
  title?: string;
  rationale?: string;
  severity?: "error" | "warn" | "info";
  weight?: number;
  tags?: string[];
  assert: Assert;
}

export interface Suite {
  $schema?: string;
  $comment?: string;
  schemaVersion: string;
  name?: string;
  description?: string;
  format?: string;
  meta?: { snapshot?: string; source?: string; [k: string]: unknown };
  extends?: string[];
  definitions?: {
    threats?: Record<string, ThreatSpec>;
    groups?: Record<string, GroupSpec>;
    predicates?: Record<string, Predicate>;
  };
  tests: Test[];
}

// ---------------------------------------------------------------------------
// Team member (parsed paste, then enriched with dex lookups)
// ---------------------------------------------------------------------------

export interface TeamMember {
  slot: number;
  nickname: string | null;
  species: string;
  item: string | null;
  ability: string | null;
  level: number;
  gender: "M" | "F" | "N" | null;
  shiny: boolean;
  teraType: string | null;
  nature: string | null;
  evs: Required<EvSpread>;
  ivs: Required<EvSpread>;
  moves: string[];
  /** Populated by the engine after dex lookup. */
  _types?: string[];
  _baseStats?: Record<StatKey, number>;
}

// ---------------------------------------------------------------------------
// Reference data shapes (data/tags.json, data/interactions.json, data/threats.json)
// ---------------------------------------------------------------------------

export interface TagEntry {
  tags: string[];
  [facet: string]: unknown;
}

export interface TagsData {
  moves?: Record<string, TagEntry>;
  items?: Record<string, TagEntry>;
  abilities?: Record<string, TagEntry>;
  species?: Record<string, TagEntry>;
  [k: string]: unknown;
}

export interface SourceNode {
  anyOf?: SourceNode[];
  all?: SourceNode[];
  type?: string | string[];
  ability?: string[];
  item?: string[];
  move?: string[];
  grounded?: boolean;
  /** Attack type(s) this entry's type-immunity check applies to, e.g. `"ground"` for Fissure. */
  typeImmuneToMove?: string | string[];
  weather?: string;
}

export interface InteractionsData {
  immunities?: Record<string, SourceNode>;
  moveTagImmunities?: Record<string, SourceNode>;
  hazardRemoval?: Record<string, SourceNode>;
  [k: string]: unknown;
}

export interface ThreatsLib {
  variations?: Record<string, Variation>;
  threats?: Record<string, ThreatSpec>;
  groups?: Record<string, GroupSpec>;
  [k: string]: unknown;
}

// ---------------------------------------------------------------------------
// Evaluation context
// ---------------------------------------------------------------------------

export interface EvalContext {
  suite: Suite;
  tags: TagsData;
  interactions: InteractionsData;
  threatsLib: ThreatsLib;
  /** $each binding inside a coverage assertion; null outside one. */
  each: string | ThreatSpec | null;
}

// ---------------------------------------------------------------------------
// Report
// ---------------------------------------------------------------------------

export interface MemberRef {
  slot: number;
  species: string;
}

export interface CoverageDetail {
  of?: "all" | "any";
  atLeast?: number;
  covered: string[];
  uncovered: string[];
  byElement: Record<string, MemberRef[]>;
}

export interface Result {
  id: string;
  title?: string;
  severity?: "error" | "warn" | "info";
  weight?: number;
  pass: boolean;
  actual?: number;
  op?: Op;
  value?: number;
  satisfiedBy?: MemberRef[];
  coverage?: CoverageDetail;
  message?: string;
  detail?: Record<string, unknown>;
}

export interface Tally {
  passed: number;
  failed: number;
}

export interface Report {
  schemaVersion: string;
  suite: string;
  team: MemberRef[];
  format?: string;
  generatedAt: string;
  passed: boolean;
  summary: Partial<Record<"error" | "warn" | "info", Tally>>;
  results: Result[];
}

/** Internal shape returned by assertion evaluators before the engine adds id/title/severity. */
export type PartialResult = Omit<Result, "id">;
